version: "3.9"
services:
  # backend:
    # depends_on:
    #   postgres-database:
    #     condition: service_healthy
  database:
    build: db/.
    image: database
    container_name: database
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
        - POSTGRES_HOST_AUTH_METHOD=password
        - POSTGRES_DOCKER_USER=${POSTGRES_DOCKER_USER}
        - POSTGRES_DOCKER_PASSWORD=${POSTGRES_DOCKER_PASSWORD}
        - POSTGRES_DOCKER_DB_NAME=${POSTGRES_DOCKER_DB_NAME}
    ports:
      - ${HOST_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_DOCKER_USER} -d ${POSTGRES_DOCKER_DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  db-data:
    driver: local
    name: database
