version: "3.9"
services:
  database:
    build: db/.
    image: db
    container_name: db
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
        - POSTGRES_HOST_AUTH_METHOD=password
        - POSTGRES_DOCKER_USER=${POSTGRES_DOCKER_USER}
        - POSTGRES_DOCKER_PASSWORD=${POSTGRES_DOCKER_PASSWORD}
        - POSTGRES_DOCKER_DB_NAME=${POSTGRES_DOCKER_DB_NAME}
    ports:
      - ${HOST_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    driver: local
    name: db
