#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username="${POSTGRES_USER}" --dbname=${POSTGRES_DB_NAME} <<-EOSQL
CREATE USER ${POSTGRES_DOCKER_USER} WITH ENCRYPTED PASSWORD '$POSTGRES_DOCKER_PASSWORD';
ALTER ROLE ${POSTGRES_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_PASSWORD}';
ALTER ROLE ${POSTGRES_DOCKER_USER} WITH SUPERUSER LOGIN;
CREATE DATABASE ${POSTGRES_DOCKER_DB_NAME} ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';
ALTER DATABASE ${POSTGRES_DOCKER_DB_NAME} OWNER TO ${POSTGRES_DOCKER_USER};
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DOCKER_DB_NAME} TO ${POSTGRES_DOCKER_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username="${POSTGRES_DOCKER_USER}" --dbname=${POSTGRES_DOCKER_DB_NAME} <<-EOSQL
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA public;
EOSQL